// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { BookkeepingAgentV2 } from "./src/edge/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    INVOICE_AGENT: __TelnyxActorNamespace<BookkeepingAgentV2>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "CONTROL_TOKEN" | "INBOX_ID" | "MODEL_ID" | "ATTACHMENT_HOSTS" | "API_KEY" | "PDF_RENDERER_URL" | "PDF_RENDERER_TOKEN"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    INVOICE_AGENT: __TelnyxActorNamespace<BookkeepingAgentV2>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "CONTROL_TOKEN" | "INBOX_ID" | "MODEL_ID" | "ATTACHMENT_HOSTS" | "API_KEY" | "PDF_RENDERER_URL" | "PDF_RENDERER_TOKEN"): Promise<string> };
  }
}

export {};
