import test from 'node:test';
import assert from 'node:assert/strict';
import {checkCompleteness,businessReference} from '../src/completeness.ts';
const item=(id,vendor='vendor-A',number=id)=>({canonicalId:id,businessReference:businessReference(vendor,number)});
const input=()=>({received:[item('1'),item('2')],expectedCount:2,expectedManifest:null,unresolvedDocuments:0});
test('B-001 count agreement is labelled count-only, not complete',()=>assert.equal(checkCompleteness(input()).status,'count_match_only'));
test('B-002 expected 20 received 18 flags shortfall',()=>{const x=input();x.expectedCount=20;x.received=Array.from({length:18},(_,i)=>item(String(i)));const r=checkCompleteness(x);assert.equal(r.status,'incomplete');assert.equal(r.countState,'short');assert.equal(r.missingReferences.length,0);});
test('B-003 no expected count means unknown',()=>{const x=input();x.expectedCount=null;assert.equal(checkCompleteness(x).status,'unknown');});
test('B-004 too many invoices require review',()=>{const x=input();x.expectedCount=1;assert.equal(checkCompleteness(x).status,'needs_review');});
test('B-005 repeated canonical ID does not inflate count',()=>{const x=input();x.received.push(item('1'));const r=checkCompleteness(x);assert.equal(r.uniqueReceived,2);assert.equal(r.duplicateOccurrences,1);});
test('B-006 exact expected manifest matches identities',()=>{const x=input();x.expectedManifest=x.received.map(i=>i.businessReference);assert.equal(checkCompleteness(x).status,'manifest_match');});
test('B-007 same counts but wrong identities do not pass',()=>{const x=input();x.expectedManifest=[x.received[0].businessReference,businessReference('vendor-A','3')];const r=checkCompleteness(x);assert.equal(r.status,'needs_review');assert.equal(r.missingReferences.length,1);assert.equal(r.unexpectedReferences.length,1);});
test('B-008 unresolved attachments block count-success status',()=>{const x=input();x.unresolvedDocuments=1;assert.equal(checkCompleteness(x).status,'needs_review');});
test('B-009 counts must be validated, never coerced',()=>{for(const n of [-1,1.5,NaN,Infinity,'2',undefined,10001]){const x=input();x.expectedCount=n;assert.throws(()=>checkCompleteness(x));}});
test('B-010 duplicate manifest entries are invalid',()=>{const x=input();x.expectedManifest=['same','same'];assert.throws(()=>checkCompleteness(x));});
test('B-011 count contradicting manifest is invalid',()=>{const x=input();x.expectedManifest=['one'];assert.throws(()=>checkCompleteness(x));});
test('B-012 unresolved business reference blocks manifest matching',()=>{const x=input();x.expectedManifest=x.received.map(i=>i.businessReference);x.received[0].businessReference=null;assert.equal(checkCompleteness(x).status,'needs_review');});
test('B-013 same invoice number at different suppliers is not merged',()=>{const x=input();x.received=[item('1','A','INV-001'),item('2','B','INV-001')];assert.equal(checkCompleteness(x).uniqueReceived,2);assert.equal(checkCompleteness(x).status,'count_match_only');});
test('B-014 conflicting values under the same canonical ID force review',()=>{const x=input();x.received.push(item('1','different-vendor'));assert.equal(checkCompleteness(x).status,'needs_review');});
test('B-015 distinct canonical IDs with same business reference force review',()=>{const x=input();x.received=[item('1','A','INV-001'),item('2','A','INV-001')];assert.equal(checkCompleteness(x).status,'needs_review');});
test('B-016 explicit empty batch is count-only agreement',()=>{const x=input();x.received=[];x.expectedCount=0;assert.equal(checkCompleteness(x).status,'count_match_only');});
test('B-017 empty unidentified batch is unknown',()=>{const x=input();x.received=[];x.expectedCount=null;assert.equal(checkCompleteness(x).status,'unknown');});
test('B-018 manifest can define expected count',()=>{const x=input();x.expectedCount=null;x.expectedManifest=x.received.map(i=>i.businessReference);assert.equal(checkCompleteness(x).status,'manifest_match');});
test('B-019 structured business references avoid delimiter collisions',()=>assert.notEqual(businessReference('a|b','c'),businessReference('a','b|c')));
test('B-020 case-sensitive reference values preserved',()=>assert.notEqual(businessReference('A','INV-001'),businessReference('A','inv-001')));
test('B-021 empty supplier or invoice reference is rejected',()=>{assert.throws(()=>businessReference('','a'));assert.throws(()=>businessReference('a',' '));});
test('B-022 source batch is not mutated',()=>{const x=input();const before=structuredClone(x);checkCompleteness(x);assert.deepEqual(x,before);});
test('B-023 malformed received records are rejected',()=>{const x=input();x.received=[null];assert.throws(()=>checkCompleteness(x));});
test('B-024 unspecified unresolved count is rejected',()=>{const x=input();delete x.unresolvedDocuments;assert.throws(()=>checkCompleteness(x));});
