import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {reviewInvoice} from '../src/reconcile.ts';
const original=JSON.parse(readFileSync(new URL('../fixtures/simple-pre-extracted.json',import.meta.url),'utf8'));
const fresh=()=>structuredClone(original);
const checkIssue=(invoice,code)=>{const r=reviewInvoice(invoice);assert.equal(r.status,'needs_review');assert.ok(r.issues.some(i=>i.code===code));return r;};

test('R-001 consistent simple net invoice',()=>{const r=reviewInvoice(fresh());assert.equal(r.status,'arithmetic_consistent');assert.equal(r.checks.length,4);});
test('R-002 incorrect printed line extension',()=>{const x=fresh();x.lines[0].quantity='3';assert.equal(checkIssue(x,'amount_mismatch').checks[0].delta,'-50.00');});
test('R-003 inconsistent subtotal is visible',()=>{const x=fresh();x.subtotal='124.00';checkIssue(x,'amount_mismatch');});
test('R-004 inconsistent gross is visible',()=>{const x=fresh();x.total='151.00';const r=checkIssue(x,'amount_mismatch');assert.equal(r.checks.at(-1).delta,'1.00');});
test('R-005 missing tax does not become zero',()=>{const x=fresh();x.tax=null;checkIssue(x,'missing_amount');});
test('R-006 explicit zero tax is different from missing',()=>{const x=fresh();x.tax='0.00';x.total='125.00';assert.equal(reviewInvoice(x).status,'arithmetic_consistent');});
test('R-007 credit notes require later supported semantics',()=>{const x=fresh();x.documentType='credit_note';checkIssue(x,'unsupported_document_type');});
test('R-008 tax-inclusive prices are not double-taxed',()=>{const x=fresh();x.pricing='tax_inclusive';checkIssue(x,'unsupported_pricing');});
test('R-009 unsupported adjustments force review',()=>{const x=fresh();x.complexities=['invoice_discount'];checkIssue(x,'unsupported_adjustments_or_tax_structure');});
test('R-010 unknown fields do not disappear silently',()=>{const x=fresh();x.shipping='10.00';checkIssue(x,'invalid_schema');});
test('R-011 unknown line fields do not disappear silently',()=>{const x=fresh();x.lines[0].discount='10.00';checkIssue(x,'invalid_line_schema');});
test('R-012 missing currency forces review',()=>{const x=fresh();x.currency=null;checkIssue(x,'currency_unresolved');});
test('R-013 numeric JSON amounts are rejected',()=>{const x=fresh();x.tax=25;checkIssue(x,'invalid_amount');});
test('R-014 negative invoice amount requires review',()=>{const x=fresh();x.tax='-1.00';checkIssue(x,'negative_amount_requires_review');});
test('R-015 small negative quantity cannot round itself into passing zero',()=>{const x=fresh();x.lines[0].quantity='-0.000001';checkIssue(x,'negative_line_requires_review');});
test('R-016 zero-decimal invoice',()=>{const x=fresh();x.minorUnits=0;assert.equal(reviewInvoice(x).status,'arithmetic_consistent');});
test('R-017 three-decimal invoice',()=>{const x=fresh();x.minorUnits=3;assert.equal(reviewInvoice(x).status,'arithmetic_consistent');});
test('R-018 printed amount beyond currency precision forces review',()=>{const x=fresh();x.tax='25.001';checkIssue(x,'invalid_amount');});
test('R-019 no lines cannot pass',()=>{const x=fresh();x.lines=[];checkIssue(x,'invalid_line_count');});
test('R-020 empty line and empty input fail closed',()=>{checkIssue({},'missing_identifier');const x=fresh();x.lines=[null];checkIssue(x,'invalid_line_schema');});
test('R-021 missing quantity cannot pass',()=>{const x=fresh();x.lines[0].quantity=null;checkIssue(x,'invalid_quantity_or_unit_price');});
test('R-022 unknown rounding policy cannot pass',()=>{const x=fresh();x.rounding='whatever_makes_it_match';checkIssue(x,'unsupported_rounding');});
test('R-023 missing complexity classification cannot pass',()=>{const x=fresh();delete x.complexities;checkIssue(x,'unsupported_adjustments_or_tax_structure');});
test('R-024 source values are never mutated',()=>{const x=fresh();x.total='151.00';const before=structuredClone(x);reviewInvoice(x);assert.deepEqual(x,before);});
test('R-025 arithmetic success is not extraction or tax/accounting approval',()=>{const r=reviewInvoice(fresh());assert.equal(r.extractionVerified,false);assert.equal(r.taxRateVerified,false);assert.equal(r.accountingApproved,false);});
test('R-026 self-consistent wrong extraction cannot be certified by this core',()=>{const x=fresh();for(const l of x.lines){l.unitPrice=String(Number(l.unitPrice)/10);l.lineNet=String(Number(l.lineNet)/10);}x.subtotal='12.50';x.tax='2.50';x.total='15.00';const r=reviewInvoice(x);assert.equal(r.status,'arithmetic_consistent');assert.equal(r.extractionVerified,false);});
test('R-027 line order does not change totals',()=>{const x=fresh();x.lines.reverse();assert.equal(reviewInvoice(x).status,'arithmetic_consistent');});
test('R-028 unsupported input shapes fail closed',()=>{for(const x of [null,undefined,[],42,'invoice'])checkIssue(x,'invalid_schema');});
test('R-029 too many lines fail before calculation',()=>{const x=fresh();x.lines=Array(1001).fill(x.lines[0]);checkIssue(x,'invalid_line_count');});
test('R-030 missing line net cannot be treated as zero',()=>{const x=fresh();x.lines[0].lineNet=null;checkIssue(x,'missing_amount');});
